version: "3"
services:

  runner-forLinux:
    build: ./forLinux
    image: git-runner-forLinux
    environment:
      - TOKEN=A5HCFAAHRCPD5SCUZPWHSHDF34DUU
      - URL=https://github.com/Expner/testGitActions
      - NAME=myRunnerLinux

  runner-forMacOC:
    build: ./forMacOS
    image: git-runner-forMacOS
    environment:
      - TOKEN=A5HCFAAHRCPD5SCUZPWHSHDF34DUU
      - URL=https://github.com/Expner/testGitActions
      - NAME=myRunnerMacOS


  runner-forWindows:
    build: ./forWindows
    image: git-runner-forWindows
    environment:
      - TOKEN=A5HCFAAHRCPD5SCUZPWHSHDF34DUU
      - URL=https://github.com/Expner/testGitActions
      - NAME=myRunnerWindows